version: '3.8'

services:
  scanner:
    build: .
    container_name: hp_custom_scanner
    privileged: true
    network_mode: host
    environment:
      - PORT=8050
      - NODE_ENV=production
    volumes:
      # Map the temporary scans directory
      - ./scans:/app/scans
      # Hardware & Driver Mappings
      - /dev/bus/usb:/dev/bus/usb
      - /var/run/dbus:/var/run/dbus
      - /etc/hp:/etc/hp
      - /var/lib/hp:/var/lib/hp
      - ~/.hplip:/root/.hplip
    restart: unless-stopped